CREATE TABLE `Game` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`home_team` INT(11) NOT NULL,
	`away_team` INT(11) NOT NULL,
	`home_goals` INT(11) NULL DEFAULT NULL,
	`away_goals` INT(11) NULL DEFAULT NULL,
	`date_` DATE NOT NULL,
	PRIMARY KEY (`id`),
	INDEX `IDX_83199EB2E5C617D0` (`home_team`),
	INDEX `IDX_83199EB2558F2381` (`away_team`),
	CONSTRAINT `FK_232B318C558F2381` FOREIGN KEY (`away_team`) REFERENCES `Team` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `FK_232B318CE5C617D0` FOREIGN KEY (`home_team`) REFERENCES `Team` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=187
;

CREATE TABLE `Team` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`address` VARCHAR(255) NOT NULL,
	`modified` DATETIME NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=214
;

CREATE TABLE `User` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(60) NOT NULL COLLATE 'utf8_unicode_ci',
	`password` VARCHAR(64) NOT NULL COLLATE 'utf8_unicode_ci',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `UNIQ_8D93D649E7927C74` (`email`)
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=27
;

CREATE TABLE `UserTeam` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
	`team_id` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `TeamFK` (`team_id`),
	INDEX `UserFK` (`user_id`),
	CONSTRAINT `TeamFK` FOREIGN KEY (`team_id`) REFERENCES `Team` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `UserFK` FOREIGN KEY (`user_id`) REFERENCES `User` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=230
;
